### ISSUE TITLE
Should not force "en" on Android

### ISSUE THREAD

**Issue by azchohfi** [aritchie/speechrecognition#1]
https://github.com/aritchie/speechrecognition/blob/29fc43326b8d827dd27c8c9133abd3966d1afeb8/Acr.SpeechRecognition.Android/SpeechRecognitionImpl.cs#L83

This is forcing Android to English only recognition.

I'm not sure that the same ExtraLanguage value can be used for ExtraLanguagePreference.

**Comment by aritchie** [comment]
You'll have to live with this for a while as it is in beta.  Multilingual support is unfortunately way down in the priorities at the moment
