### ISSUE TITLE
Feature Request - Update beta with new Permissions Plugin

### ISSUE THREAD

**Issue by galadril** [aritchie/speechrecognition#13]
Hi

Thanks for this library!
But could you please update the version with a new dependency to the latest version of 'Plugin.Permissions'

I need to update my Plugin.Permissions library but i can't 👍 
`
Unable to resolve dependencies. 'Plugin.Permissions 3.0.0.12' is not compatible with 'Plugin.SpeechRecognition 1.0.0-beta3 constraint: Plugin.Permissions (>= 2.0.0 && < 3.0.0)'.			0	
`

Thanks for the efforts

**Comment by aritchie** [comment]
I’m not supporting this plugin really anymore.  Best to fork and bring it into your own project
