### ISSUE TITLE
Not connected to the recognition service

### ISSUE THREAD

**Issue by majdaneq** [aritchie/speechrecognition#14]
Hello,

I'm having an issue with ListeningUntilPause, each time in the output I can see: "E/SpeechRecognizer(20711): not connected to the recognition service". Could you please tell me what can be the reason for this "warning/error"?

**Comment by aritchie** [comment]
Please use the issue template.  I have no idea what platform this is on.  What code you've used... have you requested the necessary permissions, etc!?

**Comment by aritchie** [comment]
Closed due to lack of response from user
