### ISSUE TITLE
error with code provided (request Permission)

### ISSUE THREAD

**Issue by Premiumlagg** [aritchie/speechrecognition#15]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [X] Android
 - [] UWP
 - [] .NET Standard
 
## Version of OS(s) listed above with issue
Android 8.1

## Version of Library
1.0.0

## Expected Behaviour
for this code,

        var granted = await CrossSpeechRecognition.Current.RequestPermission();
        if (granted == true)
        {
            // go!
        }

To have no error

## Actual Behavior
When i add the code, this line "await CrossSpeechRecognition.Current.RequestPermission();" has this error attached to it,

"IObservable' does not contain a definition for 'GetAwaiter' and no extension method 'GetAwaiter' accepting a first argument of type 'IObservable' could be found (are you missing a using directive or an assembly reference?)"

and i have NO idea why

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
This library uses reactive extensions.  You can't await an observable without referencing the extension

using System.Reactive.Linq;   or add .ToTask() to the end of the method.

**Comment by Premiumlagg** [comment]
that fixed that issue but now it is saying "Operator '==' cannot be applied to operands of type 'IObservable' and 'bool'" in the "if (granted)" part of the code

**Comment by Premiumlagg** [comment]
adding both of thoes things fixed both issues! thanx verry much for your help and VERRY fast response!! 🍡

**Comment by Premiumlagg** [comment]
No adding .ToTask(); on the end didnt fix the issue. still getting "Operator '==' cannot be applied to operands of type 'IObservable' and 'bool'" in the "if (granted)" part of the code. any ideas?

**Comment by aritchie** [comment]
Please note that this is not a support site.  You need to look at the signature that is coming back from the method.  

https://github.com/aritchie/speechrecognition/blob/master/Plugin.SpeechRecognition/ISpeechRecognizer.cs#L18

**Comment by Premiumlagg** [comment]
Okay i have converted the "granted" variable to string and toasted it and it is saying "not Supported" which i can only assume that my phone doesent support speach recognition but it does! as i have used this code,

var voiceIntent = new Intent(RecognizerIntent.ActionRecognizeSpeech);
            voiceIntent.PutExtra(RecognizerIntent.ExtraLanguageModel, RecognizerIntent.LanguageModelFreeForm);
            voiceIntent.PutExtra(RecognizerIntent.ExtraSpeechInputCompleteSilenceLengthMillis, 1500);
            voiceIntent.PutExtra(RecognizerIntent.ExtraSpeechInputPossiblyCompleteSilenceLengthMillis, 1500);
            voiceIntent.PutExtra(RecognizerIntent.ExtraSpeechInputMinimumLengthMillis, 15000);
            voiceIntent.PutExtra(RecognizerIntent.ExtraMaxResults, 1);
            voiceIntent.PutExtra(RecognizerIntent.ExtraLanguage, Java.Util.Locale.Default);
            StartActivityForResult(voiceIntent, VOICE);

which works fine!

i know this isnt a support site, but as no one really knows anything about trouble shooting this plugin, asking you, the creator, seems to be my only option.

**Comment by aritchie** [comment]
The code is all open source, so of course you can troubleshoot this yourself.

https://github.com/aritchie/speechrecognition/blob/master/Plugin.SpeechRecognition/Platforms/Android/SpeechRecognizerImpl.cs

**Comment by Premiumlagg** [comment]
yeah looking through your code gave me the solution! thanx for your help! 10/10 support1 🍡
