### ISSUE TITLE
Setup Page Needs Updating

### ISSUE THREAD

**Issue by Premiumlagg** [aritchie/speechrecognition#16]
- [X] iOS
 - [X] Android

## Version of Library
1.0.0

## Issue
You need to update the Setup page with this information 

add:
>using System.Reactive.Linq;

and change 
var granted = await CrossSpeechRecognition.Current.RequestPermission();
            if (granted == true)
            {
                //Go
            }

to 

var granted = await CrossSpeechRecognition.Current.RequestPermission();
            if (granted.ToString() == "Available")
            {
                //Go
            }

REASON:
your example get permission code doesent work and you are compleatly missing out a required USING statement to even use the plugin.

**Comment by aritchie** [comment]
Feel free to submit a PR if you find something wrong with the docs.
