### ISSUE TITLE
Speak has no parameter named cancelTask

### ISSUE THREAD

**Issue by btidoug** [aritchie/speechrecognition#2]
Trying to compile and test and I am getting an error in the SpeechDialogsImpl.cs file in the acr.speechdialogs project.

What does this mean and how can it be fixed?

![image](https://cloud.githubusercontent.com/assets/6748163/26126045/1d88cb3c-3a52-11e7-942d-d9e2370f3d02.png)

**Comment by aritchie** [comment]
I'm using a beta of the TTS plugin that has yet to be released.  In all honesty, this project hasn't been finished so it comes with zero support and the plugin itself is in early beta.

**Comment by btidoug** [comment]
Fair enough ... My project is early on as well ... just looking for a way
to record speech and convert to text in my xamarin forms app.  No bells and
whistles needed at all.  Speak -> record -> text ... done.

**Comment by aritchie** [comment]
I wouldn't count on me or this project then.  I'll take PR's for any bugs, but this project isn't on my radar right now.
