### ISSUE TITLE
iOS requires NSCalendarsUsageDescription - Should be fixed in newer permissions plugin

### ISSUE THREAD

**Issue by iane87** [aritchie/speechrecognition#22]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] iOS
 - [] Android
 - [] UWP
 - [] .NET Standard
 
## Version of OS(s) listed above with issue
14.1

## Version of Library
1.0.0

## Expected Behaviour
Should not require any unnecessary permissions

## Actual Behavior
When uploading to app store get this error:
ITMS-90683: Missing Purpose String in Info.plist - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSCalendarsUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data are required to include a purpose string. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy).

It looks like the problem is in the older Plugin.Permissions 

https://github.com/jamesmontemagno/PermissionsPlugin/issues/112

I have added the newer version to the solution Plugin.Permissions 6.0.1 but still get same error. It looks like some methods may be depreciated that this plugin is using.

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
I'm sorry but this plugin is long been closed as per the readme.  I forgot to close the issues.
