### ISSUE TITLE
Can I use (at least a subset of this) on iOS9.3.5 (iPhone4S)?

### ISSUE THREAD

**Issue by rarera** [aritchie/speechrecognition#3]
Hello, thanks a lot for this plugin.

My app just needs speech recognition, not dialogs. With my App I want to support as many iPhones as possible. Is it possible to run this on iOS9.3.5 (newest supported version for iPhone4S) ?

Thank you!
Ray

**Comment by aritchie** [comment]
Please read the readme.  This library only supports iOS10

**Comment by rarera** [comment]
Hi Aritchie,
Yes, I read the readme. My question is what would be the issues with iOS9.3.5 ?
By supporting iOS9+ you would include much more devices. iOS10+ is only supported by iPhone5 and higher. There is however a hige install base of iPhone4 devices outside the us where people change their devices less frequently.
If you cannot create a branch with a subset that only requires iOS9+, can you please share with me experience that you have with speech recognition pre iOS10, as I will then need to implement SR from the scratch.
Thanks,
Ray

**Comment by aritchie** [comment]
iOS 10 is when the built in API was released for speech recognition.  I won't be venturing outside of this.  Best of luck with your implementation

**Comment by rarera** [comment]
Ok thank you. A fallback to Bing or Google Speech API would however not be a bad idea.

**Comment by aritchie** [comment]
I look forward to your PR
