### ISSUE TITLE
Error of Unable to resolve 'reactiveui (>= 7.5.0-alpha0029)' for '.NETStandard,Version=v1.6'.				

### ISSUE THREAD

**Issue by EdwinNice** [aritchie/speechrecognition#5]
Hi,

I download the speechrecognition source and rebuild it in Visual Studio 2017, result Nuget error can't find version '7.5.0-alpha0029' of package 'reactiveui'. C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\: Package 'reactiveui.7.5.0-alpha0029' is not found on source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'. 4

I check in Nuget, the latest ReactiveUI version is 7.4.0. Pls help.

**Comment by aritchie** [comment]
This plugin is not released from beta yet so you aren't going to get a lot of help at the moment.

If you are just trying to play with it, you can get the reactiveui alpha from another nuget server - http://myget.org/F/reactiveui

**Comment by EdwinNice** [comment]
Hi Allan,

Thanks for you respond! I try to access to http://myget.org/F/reactiveui but
it only shows few lines of xml string. Is it possible for you to let me
know other url for me to get the reactiveui 7.5 alpha version or is it
possible for you to zip the dll and email me? So that I can navigate around
your speech recognition.

Appreciate and really need your assistance! Thanks.

**Comment by aritchie** [comment]
It is a nuget server.  Add it to your nuget package sources in VS: https://www.myget.org/F/reactiveui/api/v3/index.json

This is as far as I go in terms of support for this.  This forum is for defects and feature requests.

**Comment by pritish5** [comment]
Hi
I have done the same thing added nuget package sources in VS. but still getting same error

> NuGet Package restore failed for project Samples.iOS: Unable to find version '7.5.0-alpha0029' of package 'reactiveui'.
>   C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\: Package 'reactiveui.7.5.0-alpha0029' is not found on source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'.
>   https://api.nuget.org/v3/index.json: Package 'reactiveui.7.5.0-alpha0029' is not found on source 'https://api.nuget.org/v3/index.json'.
>   https://www.myget.org/F/reactiveui/api/v3/index.json: Package 'reactiveui.7.5.0-alpha0029' is not found on source 'https://www.myget.org/F/reactiveui/api/v3/index.json'
