### ISSUE TITLE
Audio input not working on Microsoft Surface but works on desktop PC with MS-Webcam

### ISSUE THREAD

**Issue by In8Beats** [aritchie/speechrecognition#9]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [] Android
 - [X] UWP
 - [] .NET Standard
 
## Version of OS(s) listed above with issue
UWP

## Version of Library
beta 3

## Expected Behaviour
Speech recognition functions with Microsoft Surface using built in microphone

## Actual Behavior
On my desktop PC with a Microsoft Webcam, the library works great. On my surface pro it doesn't respond to voice input. When I check microphone settings in control panel, all appears well. The VU Meter indicates the mic is receiving audio. 

Is there are way for me to know that the default inbuilt microphone is being used?

I get this same dysfunctional behavior on my Raspberry Pi 3 (model B) with Windows IoT Core and the MS webcam,i.e. no audio seems to be detected.

By the way, I love the simplicity of this plugin @aritchie - nice work! Hope to get your help and support soon.

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
It isn't anything I can do with the library.  There is no audio device selection in the API itself.  I do all of my testing for UWP on a surface book without issue as well.

The only thing I think it could be is a missing permission.  Did you put the proper permissions in the manifest file for the microphone?

**Comment by In8Beats** [comment]
@aritchie, really appreciate the response and input. I don't think it's permissions as it hears me speak on my desktop ok, just not on the surface or RPi. I'll try write some more code to get the audio config and dump out to debug, then I'll do some code to ensure I can record/play audio as the next step across both platforms. The only thing I can imagine is it's some kind of contention for the microphone, or the wrong mic is selected by default. For example, on My surface pro 3, the windows speech recognition enables me to select the in-built microphone array, and when I make a sound I can see the VU meter bounce up and down. So I know the mic itself is operational. I don't have Microsoft speech recognition activated, so don't think that there is some other app with Microphone in use, unless Cortana has grabbed it? 

Thanks anyway Alan, I'll check out some more options and then come back and add more learnings.

Thanks again for a very cool library, I managed to prototype my idea in hours thanks to your work.

Chris

**Comment by In8Beats** [comment]
@aritchie when I looked at my audio inputs on the Surface Pro 3, I disabled all other inputs (Headset and Stereo Mix), leaving only the internal array microphone active, and everything works well!\

I guess that counts as a solution. Maybe there is some code I could use to ensure that the speech stuff is using the mic that I hope it is using.
